import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>EVOS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          We’ll be back soon!
        </h1>

        <p className={styles.description}>
          Sorry for the inconvenience but we’re performing some maintenance at the moment. We’ll be back online shortly!
        </p>

        <p className={styles.description}>
          EVOS ESPORTS
        </p>
      </main>
    </div>
  )
}
